disp('---ENGLISH---')
disp('I''ve')
disp(preprocess('I''ve', 'e'))
disp('can''t')
disp(preprocess('can''t', 'e'))
disp('This is a regular sentence.')
disp(preprocess('This is a regular sentence.', 'e'))
disp('Ok this is a regular sentence')
disp(preprocess('Ok this is a regular sentence', 'e'))
disp('here(we)go,world;banana:sees-.go$now`k''d"w')
disp(preprocess('here(we)go,world;banana:sees-.go$now`k''d"w', 'e'))
x = 'One''two three shouldn''t I''ve';
disp(x)
disp(preprocess(x, 'e'))
x = 'One''two'' slash/itnow! w{o}r[l]d.';
disp(x)
disp(preprocess(x, 'e'))

disp('---MATH---')
disp('hello+ok-see<we>are=math')
disp(preprocess('hello+ok-see<we>are=math', 'e'))
disp('hello+ok-see<we>are=math')
disp(preprocess('hello+ok-see<we>are=math', 'f'))

disp('---FRENCH---')
disp('l''election')
disp(preprocess('l''election ', 'f'))
disp('je t''aime')
disp(preprocess('je t''aime', 'f'))
disp('j''ai')
disp(preprocess('j''ai', 'f'))
disp('qu''on')
disp(preprocess('qu''on', 'f'))
disp('qu''il')
disp(preprocess('qu''il', 'f'))
disp('puisqu''on')
disp(preprocess('puisqu''on', 'f'))
disp('lorsqu''il')
disp(preprocess('lorsqu''il', 'f'))
disp('lorsqu''il d''abord d''accord')
disp(preprocess('lorsqu''il d''abord d''accord', 'f'))
